Update harbor-values.yaml to use S3
stfc/cloud-deployed-apps pull request #10
Opened 2023-11-10 10:43 UTC by Koldstream

Related issue: https://stfc.atlassian.net/jira/software/c/projects/CLDSCRM/boards/77?selectedIssue=CLDSCRM-591

Changes:
Changed config to use S3 instead of Swift, as future versions of Harbor (3.0+) will start to move away from supporting Swift (see: https://github.com/goharbor/harbor/issues/19317)

2023-11-10 14:29 UTC, meoflynn requested changes

2023-11-10 14:29 UTC, meoflynn commented on prod-values/harbor-values.yaml
> +# is needed in the k8s cluster to provision volumes dynamically.
I think this might duplicate the two lines below?

2023-11-10 14:43 UTC, Koldstream commented on prod-values/harbor-values.yaml
> +# is needed in the k8s cluster to provision volumes dynamically.
Why yes they are indeedy.

2023-11-14 09:30 UTC, DavidFair requested changes

2023-11-14 09:30 UTC, DavidFair commented on prod-values/harbor-values.yaml
> +            #loglevel: debug
Can we remove these fields if they're not used for our s3 gateways?

2023-11-14 09:30 UTC, DavidFair commented on prod-values/harbor-values.yaml
> +            #keyid: mykeyid
Is this required or optional? If it's related to the secret could we put a comment as such

2023-11-14 09:30 UTC, DavidFair commented on prod-values/harbor-values.yaml
> +            # existingSecret: ""
Feel free to hardcode a secret name here, and we can use that in the setup process

E.g. "create a secret called `s3-harbor-creds` containing..." in the docs

2023-11-14 10:05 UTC, Koldstream commented on prod-values/harbor-values.yaml
> +            # existingSecret: ""
I'll have a look on how to create a key for both of them.

2023-11-14 10:06 UTC, Koldstream commented on prod-values/harbor-values.yaml
> +            #keyid: mykeyid
The uncommented ones are required, the accesskey and secretkey are generated when you make your ec2 creds.

2023-11-14 10:07 UTC, Koldstream commented on prod-values/harbor-values.yaml
> +            #loglevel: debug
Sure can remove them. I left them just in case we wanted to play with them in performance testing.

2023-12-11 11:28 UTC, DavidFair commented on prod-values/harbor-values.yaml
> +        # caBundleSecretName:
Nit: I think we can drop this comment completely since we're not using that field

2023-12-12 09:03 UTC, meoflynn approved these changes

2023-12-12 09:18 UTC, merged