PROTOTYPE: argocd repo with multi-cluster support
stfc/cloud-deployed-apps pull request #13
Opened 2024-03-25 09:48 UTC by anish-mudaraddi

make argocd works with multi-cluster support

Need to re-add some old config - but since it isn't being used yet, we can just re-add it from history and there's no issue writing over it for now with this commit

2024-03-25 14:35 UTC, DavidFair requested changes

2024-03-25 14:35 UTC, DavidFair commented on README.md
> +## deploying appofapps to a new cluster
Nit: Customising this template to your cluster

2024-03-25 14:35 UTC, DavidFair commented on README.md
> +Its a good idea to test changes on a development branch first with a dev cluster pointing to it to test changes before making a PR to main - see development workflow
You don't have a section called development workflow

Also I wouldn't mention this since all of our code has to be tested before it gets merged, instead a follow-up PR can add a tick list to the PR template

2024-03-25 14:35 UTC, DavidFair commented on README.md
> +  - reusing a staging cluster definition is recommended as the override values will be preserved - tweak these if it doesn't work
`staging` -> `test`

2024-03-25 14:35 UTC, DavidFair commented on README.md
> +If you're deploying an app for the first time to a cluster, you may want to push a commit with `disableAutomated` on it to begin with. If there's an error, this allows you to diagnose more easily wit
How? Where do I want to set that?

2024-03-25 14:35 UTC, DavidFair commented on README.md
> +```
IMO: We should remove this, and just keep the link to our confluence docs

I don't want to encourage people to disable ingress, because it also prevents them deploying TLS too

2024-03-25 14:35 UTC, DavidFair commented on README.md
> +
IMO this should be at the top with the usage to get someone started, since it's an essential step

2024-03-25 14:35 UTC, DavidFair commented on appofapps/kustomization.yaml
Does this kustomization do anything? I might be misunderstanding be it simple includes the app of apps which doesn't bring in any additional patches to that file

2024-03-25 14:35 UTC, DavidFair commented on charts/apps/argocd/Chart.yaml
> +    version: 6.7.*
This should be pinned to a minor version as well, so a commit based rollback brings a minor version (in-case it breaks)

2024-03-25 14:35 UTC, DavidFair commented on charts/apps/argocd/values.yaml
> +    domain: argocd.stfc.ac.uk
This will likely be set per cluster, is there way to move this into `staging` / `prod` folders instead
Also we should use an `example.com` since we don't have a DNS name allocated yet and I'm reluctant to take `argocd` on behalf of the entire org

2024-03-25 14:35 UTC, DavidFair commented on charts/apps/argocd/values.yaml
> +    # INGRESS - disable this if you're having problems and enable loadbalancer
IMO: we should get this working and not encourage LB usage because of lack of TLS termination

2024-03-25 14:35 UTC, DavidFair commented on charts/base/Chart.yaml
We should add something to the docs about bumping this version with each change

2024-03-25 14:35 UTC, DavidFair commented on charts/base/templates/apps.yaml
> +        {{- range $appName, $paths := $.Values.appValueFiles }}
Ditto about just calling it `valueFiles` for both infra and apps

2024-03-25 14:35 UTC, DavidFair commented on charts/base/values.yaml
> +      repoURL: https://github.com/anish-mudaraddi/cloud-deployed-apps.git
Can we change this to this repo, once it's merged it will become valid

2024-03-25 14:35 UTC, DavidFair commented on charts/base/values.yaml
> +  - charts/infra/capi/certs.yaml
Because of the way this is structured you can't have say an RKE cluster running our apps?

2024-03-25 14:35 UTC, DavidFair commented on charts/infra/capi/Chart.yaml
> +name: cluster-apps
Nit: Should this be `capi-dependencies`

2024-03-25 14:35 UTC, DavidFair commented on charts/infra/capi/values.yaml
> +    port: 6443
Can we move these into their own yaml file, these are values we really don't want downstream users playing with as it causes headaches.
Everything else is fine to alter

2024-03-25 14:35 UTC, DavidFair commented on clusters/vgc59244-test/cluster-patch.yaml
Can we rename this to `test-cluster` from your fed ID?

2024-03-25 14:35 UTC, DavidFair commented on clusters/vgc59244-test/kustomization.yaml
> +  path: cluster-patch.yaml
Ditto about combining this into one file?

2024-03-25 14:35 UTC, DavidFair commented on prod-values/rabbit-exporter-values.yaml
We should either leave the contents of `prod-values` where they are in this PR or migrate them to their new format?

Currently we just remove them without incorporating them at all

I don't mind a follow-up PR that removes them and migrates, but in that case we should still leave them as-is

2024-03-25 14:44 UTC, anish-mudaraddi commented on README.md
> +See `clusters/staging-management-cluster/values.yaml` for a good example
oh sorry - I deleted this directory - I can add it back in 

if you want an app you add them to the `values.yaml` file under `apps`

2024-03-25 14:49 UTC, anish-mudaraddi commented on README.md
> +  --wait
I mean sure - but lets dog-food it first please

2024-03-25 14:52 UTC, anish-mudaraddi commented on README.md
> +`kubectl patch app -n argocd appofapps --type replace -p '{"spec":{"source":{"repoURL":"https//:github.com/stfc/cloud-deployed-apps.git"}}}`
fine

2024-03-25 14:53 UTC, anish-mudaraddi commented on README.md
> +if you're adding `infra`, instead edit `infraValueFiles` in the same way
didn't you want infra and apps to be treated separately?

2024-03-25 14:57 UTC, anish-mudaraddi commented on README.md
> +Its a good idea to test changes on a development branch first with a dev cluster pointing to it to test changes before making a PR to main - see development workflow
Fine I'll remove this

2024-03-25 14:58 UTC, anish-mudaraddi commented on README.md
> +## Development workflow
I wrote this as a rough draft of how I wanted this to work. I'll drop it

2024-03-25 15:00 UTC, anish-mudaraddi commented on README.md
> +```
fine I'll remove it

2024-03-25 15:00 UTC, anish-mudaraddi commented on README.md
> +
only if you're deploying capi/infra

2024-03-25 15:02 UTC, anish-mudaraddi commented on charts/apps/argocd/Chart.yaml
> +    version: 6.7.*
fine

2024-03-25 15:06 UTC, anish-mudaraddi commented on charts/base/Chart.yaml
I have already done that

2024-03-25 15:08 UTC, anish-mudaraddi commented on charts/base/values.yaml
> +      repoURL: https://github.com/anish-mudaraddi/cloud-deployed-apps.git
I will do that as the last thing once you're happy with it

2024-03-25 15:08 UTC, anish-mudaraddi commented on charts/base/values.yaml
> +  - charts/infra/capi/certs.yaml
yes you can - you would just use the apps not the infra

2024-03-25 15:10 UTC, anish-mudaraddi commented on clusters/vgc59244-test/cluster-patch.yaml
yes

2024-03-25 15:11 UTC, anish-mudaraddi commented on clusters/vgc59244-test/kustomization.yaml
> +  path: cluster-patch.yaml
can't - it's boilerplate that's necessary to be here

2024-03-25 15:12 UTC, anish-mudaraddi commented on prod-values/rabbit-exporter-values.yaml
I'd rather remove them honestly - add them back in with follow up PRs

2024-03-25 15:13 UTC, anish-mudaraddi commented on prod-values/rabbit-exporter-values.yaml
but if you're adamant - I'll put them under `old/`

2024-03-25 15:37 UTC, anish-mudaraddi commented on README.md
> +  --wait
This is just if you want to expose argocd via loadbalancer if you don't want it self-managed. 
Do you want it to be ingress by default?

2024-03-25 15:48 UTC, anish-mudaraddi commented on charts/apps/argocd/values.yaml
> +    # INGRESS - disable this if you're having problems and enable loadbalancer
I mean it works - so ingress by default it is

2024-03-25 15:50 UTC, anish-mudaraddi commented on charts/infra/capi/values.yaml
> +    port: 6443
I don't understand - these are default values 
They aren't meant to be changed or exposed to downstream users - what good would putting them in another file do?

2024-03-25 16:15 UTC, anish-mudaraddi commented on README.md
> +```
no

2024-03-25 16:19 UTC, anish-mudaraddi commented on README.md
> +```
if you find a way to do it by all means make a PR - but for not we need both files

2024-03-25 16:19 UTC, anish-mudaraddi commented on README.md
> +See `clusters/staging-management-cluster/values.yaml` for a good example
I'm not going to add it back in - I'll change it to say look at test-cluster and I'll put some more comments in

2024-03-25 17:01 UTC, DavidFair commented on README.md
> +  --wait
Yeah please, problem with the LB method is a user's creds are effectively going plaintext over the wire

2024-03-25 17:04 UTC, DavidFair commented on charts/infra/capi/values.yaml
> +    port: 6443
I guess I'm trying to separate out things we want to say "feel free to change this" from things where if they change it they'll have a really bad time, e.g. networking details

2024-03-25 17:06 UTC, DavidFair commented on README.md
> +if you're adding `infra`, instead edit `infraValueFiles` in the same way
You've already done it, but it's still easy to see which is which:

```
valuesFiles:
  - infra/foo/values.yaml
  - apps/bar/values.yaml
```

2024-03-25 17:06 UTC, DavidFair commented on README.md
> +
Ah okay, I thought this applied to all cases

2024-03-25 18:23 UTC, anish-mudaraddi commented
I've made some changes that removes the need for Kustomize - makes this a lot better :)

2024-03-25 18:25 UTC, anish-mudaraddi commented on README.md
> +```
I mean its literally a line change but sure

2024-03-25 18:26 UTC, anish-mudaraddi commented on README.md
> +## deploying appofapps to a new cluster
I just moved this to another file - so this is irrelevant

2024-03-25 18:29 UTC, anish-mudaraddi commented on README.md
> +
I put this at the top anyway - figured chart-specific docs are pretty important

2024-03-25 18:58 UTC, anish-mudaraddi commented on charts/infra/capi/values.yaml
> +    port: 6443
I've separated it

2024-03-25 19:12 UTC, anish-mudaraddi commented on clusters/vgc59244-test/kustomization.yaml
> +  path: cluster-patch.yaml
I got rid of the need for kustomize so this isn't needed anymore

2024-03-26 11:07 UTC, DavidFair requested changes

2024-03-26 11:07 UTC, DavidFair commented on MAKING_CHANGES.md
> +Your last commit should be to change back the `gitRevision` back to `HEAD`
Can we put a task in to add CI to check that this is reset back in the future
Might be a good task for an apprentice as-per the work exposure checklist

2024-03-26 11:07 UTC, DavidFair commented on charts/base/values.yaml
> +      # default target revision to use - if cluster values don't specify
don't specify...?

2024-03-26 11:07 UTC, DavidFair commented on charts/infra/capi/networking.yaml
> +      - 130.246.208.220
Can we block this until https://github.com/stfc/cloud-capi-values/pull/16 gets merged and pull those changes into here too

2024-03-26 11:07 UTC, DavidFair commented on clusters/test-cluster/values.yaml
> +  clusterName: vgc59244-test
This doesn't match the directory name :wink: 
Might be worth adding to the CI task for common problems / mistakes

2024-03-26 11:16 UTC, anish-mudaraddi commented on clusters/test-cluster/values.yaml
> +  clusterName: vgc59244-test
my bad! - yes we need one

2024-04-05 10:10 UTC, anish-mudaraddi commented
see #14 for continuation

2024-04-05 10:10 UTC, closed without merging