DOC: create separate setup docs for each app
stfc/cloud-deployed-apps pull request #135
Opened 2024-08-21 10:10 UTC by anish-mudaraddi

Create separate markdown docs for how to setup each app we can install using this repo

2024-08-21 14:06 UTC, meoflynn commented on docs/apps/galaxy.md
> +TODO: make this easier to change!
Should we have this in a comment box or as a jira task/github issue?

2024-08-21 14:07 UTC, meoflynn commented on docs/apps/storage.md
> +> add the following config to the `<cluster-name>-apps` ApplicationSet in `apps.yaml` for your cluster
Need to add `.` between these two points as they are merged into one sentence when the md file view is generated

2024-08-21 14:08 UTC, meoflynn commented on docs/apps/storage.md
> +> TODO: We should do this automatically
Should this be a task we add in jira? Or as a github issue ?

2024-08-21 14:25 UTC, Chris-green-stfc requested changes

2024-08-21 14:25 UTC, Chris-green-stfc commented on docs/apps/argocd.md
> +A Kubernetes cluster - preferrably deployed using CAPI and running on the STFC CLoud
STFC CLoud -> STFC Cloud

2024-08-21 14:25 UTC, Chris-green-stfc commented on docs/apps/argocd.md
> +    domain: "myargocd.example.com
I think you missed a closing " at the end of the line

2024-08-21 15:28 UTC, anish-mudaraddi commented on docs/apps/galaxy.md
> +TODO: make this easier to change!
I'll create a github issue for it

2024-08-22 13:31 UTC, anish-mudaraddi commented on docs/apps/storage.md
> +> TODO: We should do this automatically
github issue created https://github.com/stfc/cloud-deployed-apps/issues/137

2024-08-22 13:31 UTC, anish-mudaraddi commented on docs/apps/galaxy.md
> +TODO: make this easier to change!
issue created https://github.com/stfc/cloud-deployed-apps/issues/136

2024-08-23 13:55 UTC, meoflynn requested changes

2024-08-23 13:55 UTC, meoflynn commented on docs/apps/galaxy.md
> +TODO: we need to make separate files for the xml and html files - having them in yaml is confusing
Could this be a GitHub issue instead of being in the docs?

2024-08-23 13:55 UTC, meoflynn commented on docs/apps/storage.md
> +Make sure that the project your cluster is built on has spare volume instances and volume storage capacity - if not, raise a ticket to cloud-support.stfc.ac.uk
`cloud-support@stfc.ac.uk`

2024-08-23 13:55 UTC, meoflynn commented on docs/apps/storage.md
> +Make sure that the project your cluster is built on is permitted to create shares and has spare share instances and share storage capacity - if not, raise a ticket to cloud-support.stfc.ac.uk
`cloud-support@stfc.ac.uk`

2024-09-04 14:34 UTC, meoflynn approved these changes

2024-09-05 07:44 UTC, Chris-green-stfc approved these changes

2024-09-10 13:59 UTC, merged