New workflow to detect if charts in cloud-deployed-apps match
stfc/cloud-deployed-apps pull request #160
Opened 2024-09-27 09:52 UTC by DaveW-STFC

The included workflow file will find any changes made under the Charts folder for the staging and prod environments.
It will then pass each of these to the bash script for comparison and return whether they match with the previous environment(s).
Please have a look over and give any thoughts on the process, code etc.

2024-09-30 12:48 UTC, anish-mudaraddi commented
@DaveW-STFC - could you squash all these test commits down into 1 or 2

2024-09-30 15:05 UTC, anish-mudaraddi requested changes
good start - a few things to consider

2024-09-30 15:05 UTC, anish-mudaraddi commented on .github/workflows/pr_copied_files.yaml
> +name: CI Copied Files Check
just a suggestion - but why don't you split this entire workflow into 2 parts:
- `check_staging_integrity` - one for comparing staging file changes with dev
- `check_prod_integrity` - one for comparing prod file changes with staging

This allows us to more clearly see where the issue is at a glance.

It also allows you to modify your script - instead of hardcoding the values `staging` and `dev` for `stagingEnv` and `devEnv` you can pass it as an argument 
- `/pr_check_copies.sh "$file" <env-to-compare-against>` - makes it more versatile in case we add more environments for instance

2024-09-30 15:05 UTC, anish-mudaraddi commented on scripts/pr_check_copies.sh
> +        if cmp -s "$file1" "$file2" && cmp -s "$file1" "$file3"; then
will this work if the file doesn't exist in the environment your comparing against? I suspect we'll need a test case for that to output nicely

2024-10-02 12:55 UTC, DaveW-STFC commented on .github/workflows/pr_copied_files.yaml
> +name: CI Copied Files Check
Will prod only be compared to staging or staging + dev?

2024-10-07 11:15 UTC, DavidFair commented on .github/workflows/pr_copied_files.yaml
> +name: CI Copied Files Check
It should be staging, as we shouldn't promote to dev -> prod without good reason 

If this job fails it indicates we should use a 2 person review, so I'm happy to just do `dev -> staging`, `staging -> prod`
If staging doesn't match someone is doing a `dev -> prod` which would fail with yours (which is what we want)

2024-10-07 11:32 UTC, DaveW-STFC commented on .github/workflows/pr_copied_files.yaml
> +name: CI Copied Files Check
I will need to update this then as i've set it to check any promotes to Prod match both staging and dev as it was mentioned in the task. There is a chance dev would not match as other changes could have gone into dev since promotion to staging. Removing the comparison to both makes it much simpler on the script side.
@anish-mudaraddi thoughts?

2024-10-07 16:49 UTC, DaveW-STFC commented on .github/workflows/pr_copied_files.yaml
> +name: CI Copied Files Check
I've simplified the script to account for this so things are much simpler.

2024-10-28 15:16 UTC, DavidFair commented on .github/workflows/pr_copied_files.yaml
> +    needs: changed_files
I'm not sure if this works with needs and the previous job fails (as it's an unusual workflow), have we tested it where something has changed at all? (e.g. adding a random file in this PR)

IIRC, `needs:` will abort the job if the previous step fails since it needs that output
However we're using it where we need the previous job to fail to run this one

2024-10-28 15:24 UTC, DaveW-STFC commented on .github/workflows/pr_copied_files.yaml
> +    needs: changed_files
We want the previous job to succeed as we are comparing the files to check if they are a direct copy from previous environment. If they are then we want to add a comment to state so. If they don't match then we do not comment and the review should be carried out as there are changes to check.

2024-11-19 13:46 UTC, merged