MAINT: remove group requirement for galaxy iris-iam login
stfc/cloud-deployed-apps pull request #181
Opened 2024-10-07 08:31 UTC by anish-mudaraddi

needed so PSDI can test this without adding them to stfc-cloud-dev group

2024-10-07 11:05 UTC, DavidFair requested changes

2024-10-07 11:05 UTC, DavidFair commented on clusters/dev/galaxy/materials-galaxy-values.yaml
> +    # allowed-group: "stfc-cloud-dev"
Won't this allow anyone in from IRIS IAM?
They should have a PSDI group we can add, and (if possible) we should retain dev access on the dev cluster

2024-10-07 12:27 UTC, meoflynn commented on clusters/dev/galaxy/materials-galaxy-values.yaml
> +    # allowed-group: "stfc-cloud-dev"
I also agree, is there an IAM group we can add for PSDI?

2024-10-07 12:31 UTC, anish-mudaraddi commented on clusters/dev/galaxy/materials-galaxy-values.yaml
> +    # allowed-group: "stfc-cloud-dev"
there isn't an IAM group  - and since the url has already been shared to PSDI and they intend to test things out -  I'm inclined to remove allowed-group. I can instead limit it to the emails of PSDI members if security is an issue

2024-10-07 13:16 UTC, DavidFair commented on clusters/dev/galaxy/materials-galaxy-values.yaml
> +    # allowed-group: "stfc-cloud-dev"
If they're aware of this limitation I'm happy to let it roll, as it's their call on balance between getting going and getting groups in

2024-10-08 13:45 UTC, anish-mudaraddi commented
I'll reopen this once PSDI reply with a replacement group or authorized email addresses

2024-10-08 13:45 UTC, closed without merging