MAINT: add Opensearch
stfc/cloud-deployed-apps pull request #189
Opened 2024-10-09 14:46 UTC by anish-mudaraddi

Add opensearch chart to dev. This uses opensearch-k8s-operator.

2024-10-09 15:42 UTC, DavidFair commented on charts/dev/opensearch/values.yaml
> +        - nodes.demo.io
We don't own this domain, so it should either be an `example.com` based domain or one we own

2024-10-09 15:47 UTC, DavidFair requested changes

2024-10-09 15:47 UTC, DavidFair commented on docs/apps/opensearch.md
> +-n opensearch-system
This should use SOPS to provide a secret at rest

2024-10-10 11:13 UTC, anish-mudaraddi commented on docs/apps/opensearch.md
> +-n opensearch-system
we'll need to think more about our appset design

2024-10-10 15:34 UTC, RJaliliSTFC approved these changes

2024-10-11 10:46 UTC, anish-mudaraddi commented on docs/apps/opensearch.md
> +-n opensearch-system
I'll make a follow up PR for this

2024-10-11 11:15 UTC, DavidFair commented on charts/dev/opensearch/templates/opensearch-nodes-ingress.yaml
> +  name: {{ .Values.clusterName }}-nodes-ingress
Nit: `worker-nodes-ingress` isn't a great name, could we have `worker-opensearch-ingress` ?

2024-10-11 11:15 UTC, DavidFair commented on charts/dev/opensearch/templates/opensearch-nodes-ingress.yaml
> +  namespace: {{ .Release.Namespace | default "opensearch" }}
This should just use the `Release.Namespace` rather than falling back to defaults which we have to spread throughout

2024-10-11 11:15 UTC, DavidFair commented on charts/dev/opensearch/templates/opensearch-cluster.yaml
> +  namespace: {{ .Release.Namespace | default .Values.namespace }}
In some places we use `Release.Namespace | default .Values.namespace`

Reading around other projects just use `Release.Namespace` so I think we can drop the values one then let ArgoCD + Helm get the NS correct (since this is overwritten by argo `Application` CRD)

2024-10-11 11:15 UTC, DavidFair commented on charts/dev/opensearch/templates/opensearch-dashboards-ingress.yaml
> +  namespace: {{ .Release.Namespace | default "opensearch-system" }}
Ditto

2024-10-11 11:15 UTC, DavidFair commented on charts/dev/opensearch/values.yaml
> +clusterName: dev-opensearch
This shouldn't be in this level of chart - since we can't `cp -r dev/opensearch staging/opensearch` with this in

Either we should leave it blank and fail the deployment if it's missing, or have something generic like `opensearch-cluster`

2024-10-11 11:15 UTC, DavidFair commented on charts/dev/opensearch/values.yaml
> +version: 2.17.0
Could we add a URL to where the versions are kept for future readers - since I assumed this would be set in the upstream chart and we implicitly get it from the version we've got pinned?

2024-10-11 11:15 UTC, DavidFair commented on charts/dev/opensearch/values.yaml
> +#    description: "Fluentbit user for sending logs"
Do we have a secret template for this like the OIDC, or is that planned for the future?

2024-10-14 11:54 UTC, anish-mudaraddi commented on charts/dev/opensearch/templates/opensearch-nodes-ingress.yaml
> +  name: {{ .Values.clusterName }}-nodes-ingress
opensearch ingress is being used for opensearch dashboards - matches the dns opensearch.nubes.stfc.ac.uk
nodes is being used for access to the nodes - i.e. the opensearch api - nodes.nubes.stfc.ac.uk

2024-10-14 12:00 UTC, anish-mudaraddi commented on charts/dev/opensearch/values.yaml
> +#    description: "Fluentbit user for sending logs"
if you need to deploy a user - you should add the hash of that user into the secret - this is documented

This actually needs updating away from using crds

2024-10-14 12:22 UTC, anish-mudaraddi commented on charts/dev/opensearch/values.yaml
> +clusterName: dev-opensearch
I will delete it to force people to provide it

2024-10-15 10:23 UTC, DavidFair approved these changes

2024-10-15 10:50 UTC, merged