ENH: Add chatops to staging
stfc/cloud-deployed-apps pull request #231
Opened 2024-12-02 14:11 UTC by khalford

### Description:

Add a Chart for chatops and an app in the dev worker cluster

### Special Notes:

---

### Submitter:

Have you:

* [ ] Labelled this PR, e.g. `bug`, `deployment`, `enhancement` ...etc.

- A `deployment` can be reviewed, and merged, by a single reviewer.
- It can only be used to deploy, change, or remove clusters based on existing patterns for staging.
- Anything involving prod, or production facing services must use the normal 2 person review.
- All other PR types require the usual PR process (e.g. 2 person).

---

### Reviewer

Have you:

* [ ] Verified this PR uses the correct label(s) based on the rules above?
* [ ] Checked if this could affect production (e.g. a global value that's changed without an override)?
* [ ] Tested setting this up, if it's not a deployment, to verify it can be redeployed with any documentation if appropriate?

2024-12-02 16:11 UTC, anish-mudaraddi requested changes
good start! The chart needs a few changes before I approve. I'll put your sops key on all dev clusters in a new PR - you can rebase your changes on-top of that once merged

2024-12-02 16:11 UTC, anish-mudaraddi commented on charts/dev/chatops/values.yaml
> +name: cloud-chatops-deployment
feel like you don't need this - as I mentioned in previous comments - you can set a hardcoded name - with some prefix like env. 

A usecase for something like this is If you want the user to specify some prefix so they can deploy multiple versions of your chart (with different names but same env) - you can set it here 

I think this is what you're using env for anyway - maybe a better name for this like `namePrefix` or something idk

2024-12-02 16:11 UTC, anish-mudaraddi commented on clusters/dev/worker/apps.yaml
> +            secretsFile: ../../../secrets/dev/worker/chatops.yaml
```suggestion
            secretsFile: ../../../secrets/dev/worker/apps/chatops.yaml
```

2024-12-02 16:11 UTC, anish-mudaraddi commented on secrets/dev/worker/apps/.sops.yaml
> +          - age1drky6caal0j2x58yzpw9tyflcpdpmcjqy8nss7zfvspszg0xfpdsyzu8s4
nice - so you've added your key and used it to make the file below - good! Now this should work fine if deployed 

Since you've encrypted your new secrets file with all keys mentioned here (including your own) - we should all be able to decrypt and validate the secrets. 

The only thing here is that you can't access any previously made secrets. To do this - we need to run `sops updatekeys` to re-encrypt the existing files to add your new key. There's a handy script in `scripts/update-secrets <environment> <clustername>` which does this for you

This can only be done by someone with a key that is shared by all files in directory - I will do this and make a commit

2024-12-03 08:05 UTC, khalford commented on charts/dev/chatops/templates/config-map.yaml
> +  \r
I made a configMap from a file using `kubectl create configmap cloud-chatops-config --from-file config.yml -n cloud-chatops` then used `kubectl describe configmap cloud-chatops-config -n cloud-chatops` to get the correct format and it gave me those carriage returns. I will remove them if it's not correct.

2024-12-03 09:48 UTC, anish-mudaraddi requested changes
you also need some docs for this chart

2024-12-03 09:48 UTC, anish-mudaraddi commented on charts/dev/chatops/secrets-templates/secrets.yaml
> +  SLACK_BOT_TOKEN: <>
you need to change this to match the values you expect in templates

```
secrets:
    slackBotToken: <>
    slackAppToken: <>
    githubToken: <>
```

2024-12-03 09:48 UTC, anish-mudaraddi commented on charts/dev/chatops/secrets-templates/secrets.yaml
> +  SLACK_BOT_TOKEN: <>
also please add comments for what each does - why its needed etc - useful for users

2024-12-03 09:48 UTC, anish-mudaraddi commented on charts/dev/chatops/templates/config-map.yaml
> +    khalford: U07P058AF51
maybe something like 
```
user-map:
    - name: khalford
      id: <>
```
more informative - might need a bit of refactoring in your code

2024-12-03 09:48 UTC, anish-mudaraddi commented on secrets/dev/worker/apps/chatops.yaml
> +    slackAppToekn: ENC[AES256_GCM,data:2gXRilzYyukxZF9dBd055Xg0uhyTIUyvF/AxX54J9r3wpNjzV+Mbozq/CiRazhUvR1wSrDy7j0f8iTgrgX5XV8IeIHASUpQJZqqRk3oq10TJjTlPcpmQSknk5yYUVT23cQ==,iv:vcbiGES6dwfi5nV+ECYKKFOh
typo

2024-12-09 11:10 UTC, anish-mudaraddi requested changes
you still need docs :)

2024-12-09 11:10 UTC, anish-mudaraddi commented on charts/dev/chatops/templates/config-map.yaml
> +    - Kalibh Halford:
if you opt for above change to secrets format - namely: 
```
users:
  - name: foo
    githubUser: ""
    slackID: ""
  - name: bar
    githubUser: "somevalue"
    slackID: "anothervalue"
```

you can do something like this 
```
data:
   config.yml: | 
    ---
   users:
      {{- range .Values.secrets.users }}
      - {{ .name }}:
          github_name: {{ .githubName | quote }}
          slack_id: {{ .slackID | quote }}
      {{- end }}
```

2024-12-09 11:10 UTC, anish-mudaraddi commented on charts/dev/chatops/templates/config-map.yaml
> +      - check-version-action
you should really make this part of values.yaml - easier to edit - makes it reusable for others outside of our team

```
repos: {{ toYaml  .Values.repos | nindent 4 }}
```

2024-12-09 11:55 UTC, anish-mudaraddi commented on charts/dev/chatops/templates/cloud-chatops.yaml
Does your container have any endpoints that needs to be called/accessed or is it purely making outbound API calls to slack/github?
If you want to accept inbound connections you need to make a service component (and ingress resource) - not sure if this applies to your stuff

2024-12-09 11:56 UTC, anish-mudaraddi requested changes

2024-12-09 11:56 UTC, anish-mudaraddi commented on charts/dev/chatops/secrets-templates/secrets.yaml
> +  SLACK_BOT_TOKEN: <>
you've not resolved this - you need to change these to match what your helm templates are expecting

2024-12-09 11:59 UTC, khalford commented on charts/dev/chatops/secrets-templates/secrets.yaml
> +  SLACK_BOT_TOKEN: <>
Yep missed that

2024-12-09 11:59 UTC, khalford commented on charts/dev/chatops/templates/cloud-chatops.yaml
No endpoints only outbound.

2024-12-09 12:04 UTC, anish-mudaraddi approved these changes

2024-12-09 13:10 UTC, gmatthews20 approved these changes

2024-12-09 13:12 UTC, merged