DOC: New documentation
stfc/cloud-deployed-apps pull request #31
Opened 2024-04-16 15:04 UTC by RJaliliSTFC

doc detailing deployment of new cluster in steps

### Description:

### Special Notes:

---

### Submitter:

Have you:

* [ ] Labelled this PR, e.g. `bug`, `deployment`, `enhancement` ...etc.

- A `deployment` can be reviewed, and merged, by a single reviewer.
- It can only be used to deploy, change, or remove clusters based on existing patterns for staging.
- Anything involving prod, or production facing services must use the normal 2 person review.
- All other PR types require the usual PR process (e.g. 2 person).

---

### Reviewer

Have you:

* [ ] Verified this PR uses the correct label(s) based on the rules above?
* [ ] Checked if this could affect production (e.g. a global value that's changed without an override)?
* [ ] Tested setting this up, if it's not a deployment, to verify it can be redeployed with any documentation if appropriate?

2024-04-16 16:06 UTC, DavidFair reviewed
Some nits and tidy up

Also I want to sign-post people on something they'd naturally do next, creating an app on the cluster they just created

2024-04-16 16:06 UTC, DavidFair commented on docs/DeployNewCluster.md
> +# Deploying a Worker Cluster from the Staging Cluster
`Nit: from an existing cluster`

Since this will also work for prod too

2024-04-16 16:06 UTC, DavidFair commented on docs/DeployNewCluster.md
> +    machineFlavor: l3.tiny
Can we remove these? If people don't have opinions we should use the defaults in the chart

It's only at 3 + 2 because I wanted to check if Argo could handle scaling the kcp and workers for example

2024-04-16 16:06 UTC, DavidFair commented on docs/DeployNewCluster.md
> +
Copy this to a new VM to continue working. You may want to read <deploying_apps link> if you're planning on creating a new app on your cluster

2024-04-17 08:01 UTC, RJaliliSTFC commented on docs/DeployNewCluster.md
> +# Deploying a Worker Cluster from the Staging Cluster
I thought the word staging meant where we 'stage' clusters not the distinction from prod/dev, ideally it would be the prod-staging and dev-staging clusters

2024-04-17 08:02 UTC, RJaliliSTFC commented on docs/DeployNewCluster.md
> +    machineFlavor: l3.tiny
I personally wanted to keep them in there as being someone who wants to think about node/worker count, having it shown where to change already is helpful

2024-04-17 08:04 UTC, RJaliliSTFC commented on docs/DeployNewCluster.md
> +
I was unsure about whether to do the ./deploy cluster-name step on this doc as then it would be 'creating a new cluster + deploying argo to it' in one doc, although when you look at the steps needed to then deploy argo it's not enough to justify a full doc, was hoping for some opinions on this

2024-04-17 08:08 UTC, RJaliliSTFC commented
Planning on going over the Read-me as well, as I think it's also  a bit unstructured. Planning on having it read more like Title: doc for step. A bit more explanation for each link.

2024-04-17 08:34 UTC, DavidFair commented on docs/DeployNewCluster.md
> +# Deploying a Worker Cluster from the Staging Cluster
Ah but you see how it's already overloaded - maybe `Deploying a worker cluster from a management cluster`?

2024-04-17 08:36 UTC, DavidFair commented on docs/DeployNewCluster.md
> +
It up to you, if it flows better a few duplicated lines are not problem - getting someone to change page for a 1-2 lines is worth the duplication
It's when entire paragraphs get duplicated it's a PITA to keep updated

2024-04-17 08:46 UTC, RJaliliSTFC commented on docs/DeployNewCluster.md
> +
Going to write some duplicate steps that flow into adding apps doc

2024-04-17 09:00 UTC, DavidFair commented on docs/DeployNewCluster.md
> +
Also for the worker case might be worth giving them this one-liner to helpfully copy from one VM to another (assuming they have Linux locally)

- Copy the kubeconfig directly from host A to B (using via the current SSH session), if you don't have agent forwarding
scp -3 user@mgmt-ip:/tmp/worker.kubeconfig user@new-vm:/tmp


As I find myself using it a lot and I imagine people with WSL will too

2024-04-17 14:05 UTC, anish-mudaraddi requested changes

2024-04-17 14:05 UTC, anish-mudaraddi commented on docs/DeployArgoandApps.md
> +  repository: <app-chart-repository>
you should also say to set the version here

2024-04-17 14:05 UTC, anish-mudaraddi commented on docs/DeployArgoandApps.md
> +  targetRevision: main
I'd remove this to avoid confusion - most people won't need to include this unless your messing with capi stuff

2024-04-17 14:05 UTC, anish-mudaraddi commented on docs/DeployNewCluster.md
> +`https://www.wikihow.com/Edit-the-Hosts-File-on-Windows#:~:text=1%20Open%20the%20Start%20menu%2C%20and%20click%20%22Computer%22.,the%20file%20directly%20to%20your%20%22etc%22...%20See%20More`
Edit this line like so:
```
[Editing Hosts file on Windows](https://www.wikihow.com/Edit-the-Hosts-File-on-Windows#:~:text=1%20Open%20the%20Start%20menu%2C%20and%20click%20%22Computer%22.,the%20file%20directly%20to%20your%20%22etc%22...%20See%20More)
```

2024-04-17 14:28 UTC, RJaliliSTFC commented on docs/DeployArgoandApps.md
> +- name: <app-name>
Resolved

2024-04-17 14:30 UTC, RJaliliSTFC commented on docs/DeployArgoandApps.md
> +  targetRevision: main
Resolved

2024-04-17 14:31 UTC, RJaliliSTFC commented on docs/DeployNewCluster.md
> +`https://www.wikihow.com/Edit-the-Hosts-File-on-Windows#:~:text=1%20Open%20the%20Start%20menu%2C%20and%20click%20%22Computer%22.,the%20file%20directly%20to%20your%20%22etc%22...%20See%20More`
Resolved

2024-04-17 14:34 UTC, anish-mudaraddi approved these changes

2024-04-18 08:18 UTC, DavidFair approved these changes

2024-04-18 08:18 UTC, merged