Changed default node labels
stfc/cloud-deployed-apps pull request #33
Opened 2024-04-18 08:56 UTC by RJaliliSTFC

### Description:
Added a default node label to make nodes longhorn stores 
Changed docs to reflect this

### Special Notes:

---

### Submitter:

Have you:

* [ ] Labelled this PR, e.g. `bug`, `deployment`, `enhancement` ...etc.

- A `deployment` can be reviewed, and merged, by a single reviewer.
- It can only be used to deploy, change, or remove clusters based on existing patterns for staging.
- Anything involving prod, or production facing services must use the normal 2 person review.
- All other PR types require the usual PR process (e.g. 2 person).

---

### Reviewer

Have you:

* [ ] Verified this PR uses the correct label(s) based on the rules above?
* [ ] Checked if this could affect production (e.g. a global value that's changed without an override)?
* [ ] Tested setting this up, if it's not a deployment, to verify it can be redeployed with any documentation if appropriate?

2024-04-18 13:53 UTC, DavidFair approved these changes
LGTM, I saw it recreate the MD and the nodes came up with the annotation:

```
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=david-pr-test-default-md-0-5f47d3be-zd55w
                    kubernetes.io/os=linux
                    longhorn.store.nodeselect/longhorn-storage-node=true
```

2024-04-18 14:40 UTC, anish-mudaraddi requested changes

2024-04-18 14:40 UTC, anish-mudaraddi commented on docs/DEPLOYING_APPS.md
> -## 1. Label nodes to run longhorn on
I'd still keep this - just make it clear that you'd only need this if you use something other than CAPI to deploy your cluster

2024-04-18 15:00 UTC, anish-mudaraddi requested changes

2024-04-18 15:00 UTC, anish-mudaraddi commented on docs/DEPLOYING_APPS.md
> +**NOTE:** If you're using `capi` or any other `infra` that you're also managing with argocd - make sure you set these labels accordingly for your cluster.
```suggestion
**NOTE:** If you're NOT using `capi` - make sure you set these labels accordingly for your cluster. 	
```

2024-04-18 15:00 UTC, anish-mudaraddi commented on docs/DEPLOYING_APPS.md
> +For `capi` you can set node labels like so:
```suggestion
If you want to change the node labels that capi uses - you can do so like this: 
```

2024-04-18 15:00 UTC, anish-mudaraddi commented on docs/DEPLOYING_APPS.md
> +# 1. Label nodes to run longhorn on
```suggestion
# 1. (Optional) Label nodes to run longhorn on
```

2024-04-18 15:00 UTC, anish-mudaraddi commented on docs/DEPLOYING_APPS.md
> +Make sure you have labelled your nodes so that longhorn can use them as storage nodes. You want to label your worker nodes, the default label is `longhorn.demo.io/longhorn-storage-node=true` but you
```suggestion
Make sure you have labelled your nodes so that longhorn can use them as storage nodes. 

If you're also managing `capi`, these are set for you - so you don't need to do anything.  

You want to label your worker nodes, the default label is `longhorn.demo.io/longhorn-storage-node=true`  

You can change this in the cluster-specific values like so:	
```

2024-04-22 13:16 UTC, anish-mudaraddi approved these changes

2024-04-22 13:16 UTC, merged