Add cert manager
stfc/cloud-deployed-apps pull request #43
Opened 2024-04-19 16:33 UTC by DavidFair

### Description:
Adds cert manager as a global item, as per the documentation https://cert-manager.io/docs/installation/helm/#installing-cert-manager-as-subchart
Since we can only have one `cloud-deployed-apps` (and only an app would use it) we use it as a dependency.

By default we enable it with the self-signed issuer. This should encourage developers to test with cert-manager and make it easy to switch to a trusted provider later, unifying the dev and prod paths in most cases.

### Special Notes:

- This should be tested against an existing pre-deployed cluster too, by pointing it to this branch. As we should verify that Argo is smart enough to fetch the dependencies, since helm wasn't during `deploy.sh`

---

### Submitter:

Have you:

* [x] Labelled this PR, e.g. `bug`, `deployment`, `enhancement` ...etc.

- A `deployment` can be reviewed, and merged, by a single reviewer.
- It can only be used to deploy, change, or remove clusters based on existing patterns for staging.
- Anything involving prod, or production facing services must use the normal 2 person review.
- All other PR types require the usual PR process (e.g. 2 person).

---

### Reviewer

Have you:

* [ ] Verified this PR uses the correct label(s) based on the rules above?
* [ ] Checked if this could affect production (e.g. a global value that's changed without an override)?
* [ ] Tested setting this up, if it's not a deployment, to verify it can be redeployed with any documentation if appropriate?

2024-04-19 16:59 UTC, anish-mudaraddi requested changes
looks fine - few comments

2024-04-19 16:59 UTC, anish-mudaraddi commented on scripts/deploy.sh
> +helm dependency update ../charts/argocd-apps
just curious - do you need to do this? Thought argo does this for you

2024-04-19 16:59 UTC, anish-mudaraddi commented on scripts/deploy.sh
> +kubectl create namespace cert-manager || true
argocd should create the namespace for you

2024-04-19 16:59 UTC, anish-mudaraddi commented on charts/argocd-apps/values.yaml
> -  - charts/apps/longhorn/values.yaml
why'd you get rid of this? 
atm we need to define default values files for all our apps this way - so add this back

2024-04-19 17:14 UTC, anish-mudaraddi commented
maybe think about deploying cert-manager with a standalone application rather than it being tied with cloud-deployed-apps - therefore it will be more stable on prod - look at the way argocd application is defined here - https://github.com/stfc/cloud-deployed-apps/blob/main/charts/argocd-apps/templates/argocd-app.yaml

2024-04-23 08:34 UTC, DavidFair commented on scripts/deploy.sh
> +helm dependency update ../charts/argocd-apps
Unfortunately, to get the app installed into Argo CD helm needs the dependencies including cert-manager up-front
Once it's created then yeah Argo does the rest

2024-04-23 08:35 UTC, DavidFair commented on charts/argocd-apps/values.yaml
> -  - charts/apps/longhorn/values.yaml
It works without this though?
Since our other apps including the one in `setup_harbor_infra` doesn't include these lines but still grabs `values.yaml` values

2024-04-23 08:43 UTC, DavidFair commented
> maybe think about deploying cert-manager with a standalone application rather than it being tied with cloud-deployed-apps - therefore it will be more stable on prod - look at the way argocd application is defined here - https://github.com/stfc/cloud-deployed-apps/blob/main/charts/argocd-apps/templates/argocd-app.yaml

https://cert-manager.io/docs/installation/helm/#installing-with-helm

As per the docs we need to...

> Be sure never to embed cert-manager as a sub-chart of other Helm charts; cert-manager manages non-namespaced resources in your cluster and care must be taken to ensure that it is installed exactly once.

As this application can only be installed once, it guards against something akin to:

```
apps:
  - name: foo  # brings the cert-manager dep
  - name: cert-manager
```

We could just move it to an app and guard against it in PRs, but I want to make it so even self-signed certs uses the same mechanism - thoughts?

2024-04-24 12:36 UTC, anish-mudaraddi commented on charts/argocd-apps/values.yaml
> -  - charts/apps/longhorn/values.yaml
huh, are you 100% sure that works? Guess if a `values.yaml` is next to the `Chart.yaml` it automatically picks it up

2024-04-24 12:45 UTC, anish-mudaraddi commented
@DavidFair - see this branch with a commit on how I think you should add cert-manager as a single-use app 
https://github.com/stfc/cloud-deployed-apps/tree/updated-cert-manager

benefits of this: you decouple `cert-manager` from `cloud-deployed-apps` - single responsibility principle. 
It's more stable

2024-04-24 15:05 UTC, DavidFair commented
If we do it as a standalone argo app - is there a way to turn an application off or on through it?
I like the idea that we use `cert-manager.enabled` to toggle it at an Argo level rather than the dependency

2024-04-30 14:34 UTC, anish-mudaraddi approved these changes

2024-04-30 14:36 UTC, anish-mudaraddi commented on clusters/david-pr-test/app-values.yaml
> +      targetRevision: Add_cert_manager
This will need to be changed back to main - or better yet the test cluster can be cleaned up in a followup PR

2024-05-01 14:10 UTC, RJaliliSTFC commented on charts/argocd-apps/Chart.yaml
Are we incrementing the version every time we add a new app?

2024-05-01 14:18 UTC, DavidFair commented on clusters/david-pr-test/app-values.yaml
> +      targetRevision: Add_cert_manager
I'll do a follow-up PR to remove this

2024-05-01 14:19 UTC, DavidFair commented on charts/argocd-apps/Chart.yaml
In this case it's because I've changed the chart itself by adding a new file to the `templates` directory, if we change the files in this directory we should do a semver bump

Adding a new app, since it's a different dir, we'd bump the version there instead

2024-05-02 08:56 UTC, merged