Env values
stfc/cloud-deployed-apps pull request #6
Opened 2023-10-03 08:34 UTC by RJaliliSTFC

Changes to allow for prod/dev values file structure and easy deployment of different environments

2023-10-03 11:00 UTC, meoflynn requested changes

2023-10-03 11:05 UTC, RJaliliSTFC commented on prod-values/rabbit-consumer-values.yaml
This is directly copied from https://github.com/stfc/SCD-OpenStack-Utils/blob/master/charts/rabbit-consumer/prod-values.yaml I am unsure if this is intentional, I can ask David if you are unsure

2023-10-03 12:05 UTC, meoflynn commented on prod-values/rabbit-consumer-values.yaml
Yeah I think double check with David (I think I had almost the same question with the rabbit consumers before when I saw that the prod and dev `values.yaml` files were pointing to prod and dev separately but used the same project ID a while ago but I can't remember 😅 )

2023-10-04 12:26 UTC, DavidFair commented on prod-values/rabbit-consumer-values.yaml
They used to be the same values, it should now be `c9aee696c4b54f12a645af2c951327dc` for dev

2023-10-05 08:12 UTC, meoflynn commented on templates/rabbit-consumers.yaml
> +    targetRevision: b9cd82fcbb07d14bded62e0dbe3eb51bc7f15f4c
Would this have to be changed manually when the rabbit consumer chart is updated in the future?

2023-10-05 08:15 UTC, RJaliliSTFC commented on templates/rabbit-consumers.yaml
> +    targetRevision: b9cd82fcbb07d14bded62e0dbe3eb51bc7f15f4c
Yes this is intentional, in a future PR i need to change this to be a templated value so that prod can have a fixed target revision and dev can have HEAD

2023-10-05 08:20 UTC, RJaliliSTFC commented on templates/rabbit-exporter.yaml
>      targetRevision: 706ee46f37f9762f1202f494708e9afbfa14a23b
Same thing, I need to write a pr to make it a templated value

2023-10-05 08:40 UTC, meoflynn commented on prod-values/rabbit-consumer-values.yaml
Okay, we should update the rabbit consumer chart `dev-values.yaml` in a future PR as well

2023-10-05 09:47 UTC, meoflynn approved these changes

2023-10-05 09:47 UTC, merged