FEAT: use folder-based flows
stfc/cloud-deployed-apps pull request #95
Opened 2024-06-13 12:17 UTC by anish-mudaraddi

### Description:
This PR changes the way we use argocd to use folder-based flows
We've been successfully testing this flow on this feature branch so it is ready to go

### Special Notes:

---

### Submitter:

Have you:

* [ ] Labelled this PR, e.g. `bug`, `deployment`, `enhancement` ...etc.

- A `deployment` can be reviewed, and merged, by a single reviewer.
- It can only be used to deploy, change, or remove clusters based on existing patterns for staging.
- Anything involving prod, or production facing services must use the normal 2 person review.
- All other PR types require the usual PR process (e.g. 2 person).

---

### Reviewer

Have you:

* [ ] Verified this PR uses the correct label(s) based on the rules above?
* [ ] Checked if this could affect production (e.g. a global value that's changed without an override)?
* [ ] Tested setting this up, if it's not a deployment, to verify it can be redeployed with any documentation if appropriate?

2024-06-13 13:44 UTC, meoflynn requested changes
Just did a quick initial review

2024-06-13 13:44 UTC, meoflynn commented on docs/pics/diagram.drawio
Could we update the diagram to be a PNG file instead of `.drawio`

2024-06-13 13:44 UTC, meoflynn commented on charts/dev/capi-infra/values.yaml
> +  # this expires 2023-12-05T23:59:59Z (UTC)
I don't think this is the right expiry date?

2024-06-13 13:44 UTC, meoflynn commented on charts/staging/capi-infra/values.yaml
> +  # this expires 2023-12-05T23:59:59Z (UTC)
This doesn't seem like the right date

2024-06-13 13:48 UTC, meoflynn commented on charts/staging/capi-infra/values.yaml
> +  # this expires 2023-12-05T23:59:59Z (UTC)
Discussed in-person, certificate is still valid

2024-06-13 13:48 UTC, meoflynn commented on charts/dev/capi-infra/values.yaml
> +  # this expires 2023-12-05T23:59:59Z (UTC)
Discussed in-person, certificate is still valid

2024-06-13 15:10 UTC, anish-mudaraddi commented on docs/pics/diagram.drawio
this is so you can update the diagrams in https://app.diagrams.net

2024-06-13 15:14 UTC, meoflynn approved these changes

2024-06-14 00:17 UTC, DavidFair approved these changes

2024-06-14 00:17 UTC, merged